name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover

      - name: Install pipenv
        run: python -m pip install pipenv
      - name: Pipenvlock
        run: pipenv lock
      - name: Pipenvsync
        run: |
          pipenv sync
      - name: Start tests
        run: pipenv run python -m pytest test_main.py

      # Дополнительные шаги для сборки и тестирования вашего приложения
